### PR TITLE
Add download to generation step

### PR DESCRIPTION
**Pull request by cugu**
Solves #17

### CODE REVIEW

**Comment by tatsu-i** [comment]
Where is the list of currently supported artifacts defined?

Step 4  `Edit pack/ac.yaml and add the artifacts you want to collect.`

**Comment by cugu** [comment]
What currently is missing is the artifacts from https://github.com/forensicanalysis/artifacts/. Those need to go into `pack/artifacts/`. Anyway those are supplied with a different license so I do not want to simply copy those over.

**Comment by tatsu-i** [comment]
thanks.
I was able to solve it with the following steps.

```
$ git clone https://github.com/forensicanalysis/artifactcollector
$ git clone https://github.com/forensicanalysis/artifacts/ -b v0.6.1 /tmp/artifacts
$ cp /tmp/artifacts/*.yaml artifactcollector/pack/artifacts/
$ cd artifactcollector && go generate
```

**Comment by tatsu-i** [comment]
It looks like your CI is failing, but you need to quote it. Pulled request for fixed branch.

**Pull request merged**
